spring:
  application:
    name: demo-provider
  profiles:
    active: project
  cloud:
    config:
      enabled: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true

  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
server:
  port: 8001
  max-http-header-size: 102400
  shutdown: graceful


